### ISSUE TITLE
Solidity compilation fail with SIGSEGV 

### ISSUE THREAD

**Issue by pandadefi** [matter-labs/zksync-v2-issues#18]
**Describe the issue**

```
Error: Command failed: /Users/panda/Library/Caches/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.2.0 --standard-json   --solc /Users/panda/Library/Caches/hardhat-nodejs/compilers-v2/macosx-amd64/solc-macosx-amd64-v0.8.16+commit.07a7930e

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12) {
  killed: false,
  code: null,
  signal: 'SIGSEGV',
  cmd: '/Users/panda/Library/Caches/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.2.0 --standard-json   --solc /Users/panda/Library/Caches/hardhat-nodejs/compilers-v2/macosx-amd64/solc-macosx-amd64-v0.8.16+commit.07a7930e'
```

**Expected behavior**

Contract should compile

**To Reproduce**

> Clone https://github.com/pandadefi/registry/commit/7107cf19e8430c7aac664c279cce57c1ed4f81b5
> yarn
> yarn hardhat compile

**Comment by bxpana** [comment]
@pandadefi we have a new version of the compiler out `1.2.3` but looks like it's missing from https://github.com/matter-labs/zkvyper-bin. Once we have that updated we'll give you a heads up so you can try again.

**Comment by bxpana** [comment]
@pandadefi turns out only zksolc needs `1.2.3` for now you can use the latest for zkvyper `1.2.2`. Can you update that and see if you get the same error?

**Comment by pandadefi** [comment]
solved
